<h1><?php echo $title; ?></h1>

<div class="list-categorie">
	<?php foreach ($categories as $categorie): ?>
		
		<div class="clearfix">
			<h3><?php echo $categorie['titre']; ?></h3>
			<span> Actuellement : 
			<?php echo $stats['numberTopic'][$categorie['id']]['nbr_topic']; ?> 
			sujet<small>(s)</small> / 
			<?php echo $stats['numberTopic'][$categorie['id']]['nbr_message']; ?>
			message<small>(s)</small>.
			</span>
		</div>
		
		<?php if ($this->connect): ?>
		<span><a class="createNewTopic" href="?page=new_topic&amp;categorieId=<?php echo $categorie['id']; ?>">Créer un nouveau sujet</a></span>
		<?php endif; ?>

<!-- 
	*******************************************************
		AFFICHAGE DES TOPICS DE LA CATEGORIE EN COURS
	*******************************************************
-->
		<ul>
			<?php foreach ($topics as $topic): ?>
			<?php $date = new DateTime($topic['topic_date_create']); ?>
				<?php if ($topic['categorie_id'] == $categorie['id']) : ?>
					<li class="clearfix">
						<p> 
							<a class="<?php if (!$topic['view']) { echo 'notView'; }?>" href="?page=topic&amp;topicId=<?php echo $topic['id']; ?>">
							<i class="fa fa-comments"></i> 
							<?php echo $topic['titre']; ?>
							</a>

							<span class="writeBy">
								écrit par : 
								<?php echo $topic['user_pseudo']; ?> 
								le <?php $date = new DateTime($topic['topic_date_create']);
								echo $date->format("d/m/Y à H:i"); ?> .
								Dernier message de : xxx.
							</span>
	
							<?php if (!$topic['view']): ?>
							<span class="topic-new-msg">
								<i class="fa fa-envelope-o"></i>
								Nouveau message
							</span>
							<?php endif; ?>
							
						</p>

						<span>
							<?php echo $stats['numberMessage'][$topic['id']]; ?> 
							message(s)
						</span>
					</li>
				<?php endif; ?>
			<?php endforeach; ?>
		</ul>

	<?php endforeach; ?>
</div>
