<form action="?page=handlingConnection" method="post">
	<input type="text" name="pseudo" placeholder="Pseudo...">
	<input type="password" name="password" placeholder="Mot de passe">
	<input type="submit" value="Connexion">
</form>

<ul class="menu-connect">
	<li><a href="?page=accueil"><i class="fa fa-home"></i> Accueil</a></li>
	<li><a href="?page=inscription"><i class="fa fa-user-plus"></i> Inscription</a></li>
</ul>

