		</div>
	</main>

	<footer>
		<div class="wrapper">
			<p>&copy; Forum de dingue. Vive la promo 39.</p>
		</div>
	</footer>


	    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
		<script src="js/vendor/tinymce/tiny_mce.js"></script>
        <script src="js/main.js"></script>
	</body>
</html>