<!doctype html>
<html>
	<head>
		<title><?php echo $title; ?></title>
		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="css/normalize.min.css">
        <link rel="stylesheet" href="css/main.css">

        <script src="js/vendor/modernizr-2.8.3.min.js"></script>
	</head>

	<body>
		<header>
			<nav class="wrapper clearfix">
				<?php 
					if ($this->connect) {
						include __ROOT_DIR__ . '/views/nav.phtml';
					}
					else {
						include __ROOT_DIR__ . '/views/connection.phtml';
					}

				?>
			</nav>
		</header>
		
		<main>

			<?php 

			/*****************************************
			AFFICHAGE DES MESSAGES D ALERTES
			*****************************************/

			if (isset($this->session['informationUser'])): ?>
				<div class="wrapper">
					<div class="alert">
						
						<div>
							<?php foreach ($this->session['informationUser'] as $value): ?>
								<p>
								<?php echo $value; ?>	
								</p>					 
							<?php endforeach; ?>
						</div>
						
					</div>
				
				</div>
			<?php 
			unset($this->session['informationUser']);
			endif; ?>

			<div class="wrapper">

			